import { StyleSheet } from 'react-native';

export const getResponsiveStyles = (width, height, isPhone, isTablet, sidebarExpanded, chatVisible) => {
  const headerHeight = isPhone ? 60 : 70;
  const sidebarWidth = isPhone ? width * 0.75 : (isTablet ? 240 : 260);
  const contentPadding = isPhone ? 16 : (isTablet ? 24 : 50);
  const contentHorizontalPadding = isPhone ? 16 : (isTablet ? 32 : 80);
  
  return StyleSheet.create({
    container: {
      flexDirection: isPhone ? 'column' : 'row',
      height: '100%',
      backgroundColor: '#0b1120',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#1e293b',
      paddingVertical: 10,
      paddingHorizontal: isPhone ? 16 : 20,
      borderBottomColor: '#334155',
      borderBottomWidth: 1,
      zIndex: 999,
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: headerHeight,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerLogo: {
      width: isPhone ? 40 : 30,
      height: isPhone ? 24 : 30,
      marginRight: 10,
      borderRadius: 6,
    },
    headerTitle: {
      color: '#fff',
      fontSize: isPhone ? 18 : 20,
      fontWeight: 'bold',
    },
    profileImage: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: '#fff',
    },
    profileMenu: {
      position: 'absolute',
      top: headerHeight,
      right: 20,
      backgroundColor: '#1e293b',
      padding: 10,
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    menuItemText: {
      color: '#fff',
      fontSize: 14,
      paddingVertical: 6,
    },
    sidebar: {
      backgroundColor: '#1e293b',
      paddingTop: headerHeight + 10,
      justifyContent: 'space-between',
      width: sidebarWidth,
      height: isPhone ? 'auto' : '100%',
      borderRightWidth: 1,
      borderRightColor: '#334155',
    },
    sidebarExpanded: {
      width: sidebarWidth,
    },
    sidebarCollapsed: {
      width: isPhone ? 0 : 60,
    },
    drawerOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-start',
      paddingTop: headerHeight,
    },
    drawerContent: {
      backgroundColor: '#1e293b',
      width: sidebarWidth,
      height: '100%',
      paddingTop: 15,
      borderRightWidth: 1,
      borderRightColor: '#334155',
    },
    sidebarScroll: {
      paddingHorizontal: 8,
      paddingVertical: 5,
    },
    menuItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 5,
      marginVertical: 6,
      borderRadius: 8,
      minHeight: 40,
    },
    menuItemActive: {
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
      borderLeftWidth: 3,
      borderLeftColor: '#3b82f6',
    },
    menuLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    iconOnly: {
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
    },
    icon: {
      marginRight: sidebarExpanded ? 10 : 0,
      textAlign: 'center',
      width: 16,
    },
    menuText: {
      color: '#e2e8f0',
      fontSize: 13,
      fontWeight: '500',
      flex: 1,
    },
    arrowIcon: {
      marginLeft: 8,
      width: 12,
    },
    submenu: {
      marginLeft: 8,
      marginTop: 2,
      backgroundColor: 'rgba(15, 23, 42, 0.5)',
      borderRadius: 6,
      paddingVertical: 4,
    },
    submenuItem: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginVertical: 1,
      borderRadius: 4,
      minHeight: 36,
      flexDirection: 'row',
      alignItems: 'center',
    },
    submenuItemActive: {
      backgroundColor: 'rgba(59, 130, 246, 0.15)',
    },
    submenuText: {
      color: '#94a3b8',
      fontSize: 12,
      fontWeight: '400',
      marginLeft: 4,
    },
    submenuDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: '#64748b',
      marginRight: 8,
    },
    logoutContainer: {
      padding: 10,
      borderTopWidth: 1,
      borderTopColor: '#334155',
      marginTop: 10,
    },
    floatingToggle: {
      position: 'absolute',
      top: isPhone ? headerHeight + 10 : '90%',
      left: isPhone ? 20 : (sidebarExpanded ? sidebarWidth - 20 : 40),
      transform: [{ translateY: -20 }],
      zIndex: 1000,
      borderRadius: 12,
      overflow: 'hidden',
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    toggleSidebarBtn: {
      width: 40,
      height: 40,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 0,
      shadowColor: 'transparent',
    },
    content: {
      flex: 1,
      padding: contentPadding,
      backgroundColor: '#0f172a',
      paddingHorizontal: contentHorizontalPadding,
      paddingTop: headerHeight + contentPadding,
      marginRight: (chatVisible && !isPhone) ? 280 : 0,
    },
    welcomeCard: {
      backgroundColor: '#1e293b',
      padding: 16,
      borderRadius: 12,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: '#334155',
    },
    welcomeText: {
      color: '#fff',
      fontSize: isPhone ? 18 : 20,
      fontWeight: 'bold',
    },
    welcomeCorreo: {
      color: '#94a3b8',
      fontSize: isPhone ? 13 : 14,
      marginTop: 4,
    },
    cardGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: isPhone ? 8 : 12,
    },
    statCard: {
      backgroundColor: '#1e293b',
      padding: isPhone ? 25 : 16,
      borderRadius: 18,
      width: '31%',
      alignItems: 'center',
      marginBottom: isPhone ? 8 : 12,
      borderWidth: 1,
      borderColor: '#334155',
      minHeight: isPhone ? 80 : 100,
    },
    statLabel: {
      color: '#94a3b8',
      fontSize: isPhone ? 11 : 14,
      marginTop: isPhone ? 4 : 8,
      textAlign: 'center',
    },
    statValue: {
      color: '#fff',
      fontSize: isPhone ? 14 : 18,
      fontWeight: 'bold',
      marginTop: 4,
      textAlign: 'center',
    },
    botonToggleChat: {
      position: 'absolute',
      right: 20,
      bottom: 30,
      backgroundColor: '#3b82f6',
      padding: 12,
      borderRadius: 12,
      zIndex: 999,
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    chatPanel: {
      position: 'absolute',
      right: 0,
      top: headerHeight,
      bottom: 0,
      width: isPhone ? '100%' : (isTablet ? '50%' : 280),
      backgroundColor: '#1e293b',
      padding: 15,
      zIndex: 998,
      borderLeftWidth: 1,
      borderLeftColor: '#334155',
    },
    chatTitle: {
      color: '#fff',
      fontSize: isPhone ? 18 : 20,
      fontWeight: 'bold',
      marginBottom: 10,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#334155',
    },
    chatMensajes: {
      flex: 1,
      marginBottom: 10,
    },
    mensaje: {
      padding: 10,
      marginVertical: 4,
      marginHorizontal: 6,
      borderRadius: 12,
      maxWidth: '80%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    mensajePropio: {
      backgroundColor: '#3b82f6',
      alignSelf: 'flex-end',
      borderTopRightRadius: 4,
    },
    mensajeOtro: {
      backgroundColor: '#334155',
      alignSelf: 'flex-start',
      borderTopLeftRadius: 4,
    },
    mensajeTexto: {
      color: '#fff',
      fontSize: 14,
      lineHeight: 18,
    },
    chatInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#334155',
      borderRadius: 80,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 50,
      maxHeight: 120,
      borderWidth: 5,
      borderColor: '#475569',
    },
    chatInput: {
      flex: 1,
      color: '#fff',
      fontSize: 14,
      paddingRight: 8,
      paddingVertical: 8,
      textAlignVertical: 'top',
      maxHeight: 100,
    },
    botonCerrarChat: {
      position: 'absolute',
      top: 5,
      right: 10,
      zIndex: 999,
      backgroundColor: '#475569',
      padding: 8,
      borderRadius: 6,
      minWidth: 32,
      minHeight: 32,
      justifyContent: 'center',
      alignItems: 'center',
    },
    typingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      marginVertical: 4,
      marginHorizontal: 6,
      backgroundColor: '#334155',
      borderRadius: 12,
      maxWidth: '80%',
      alignSelf: 'flex-start',
    },
    typingDots: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 8,
    },
    typingDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: '#94a3b8',
      marginHorizontal: 2,
    },
  });
};