import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#0f172a', 
    padding: 16 
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: { 
    color: '#ffffff', 
    fontSize: 24, 
    fontWeight: 'bold' 
  },
  buscador: {
    flexDirection: 'row',
    backgroundColor: '#1e293b',
    borderRadius: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#334155',
    minHeight: 50,
  },
  inputText: {
    color: '#ffffff',
    flex: 1,
    paddingVertical: 12,
    marginLeft: 12,
    fontSize: 16,
  },
  botoneraDerecha: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  botonAgregar: {
    backgroundColor: '#22c55e',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  btnExportarExcel: {
    backgroundColor: '#3b82f6',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  btnExportarPDF: {
    backgroundColor: '#f59e0b',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  btnEliminar: {
    backgroundColor: '#ef4444',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnEditar: {
    backgroundColor: '#eab308',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnAbonar: {
    backgroundColor: '#22c55e',
    
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnEntregar: {
    backgroundColor: '#3b82f6',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnVerDetalles: {
    backgroundColor: '#6b7280',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnVolver: {
    backgroundColor: '#6b7280',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  botonTexto: { 
    color: '#ffffff', 
    fontWeight: '600', 
    fontSize: 14 
  },
  lista: { 
    flex: 1 
  },
  card: {
    backgroundColor: '#1e293b',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#334155',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  cardGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  infoCompleta: {
    flex: 3,
    paddingRight: 16,
  },
  nombre: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 6,
  },
  info: {
    color: '#cbd5e1',
    fontSize: 14,
    marginTop: 4,
  },
  label: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 8,
    marginBottom: 4,
  },
  materialTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
    marginBottom: 10,
  },
  materialTag: {
    backgroundColor: '#4b5563',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
  },
  materialTagText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
  },
  tipoMaterialTag: {
    backgroundColor: '#374151',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
  },
  tipoMaterialTagText: {
    fontSize: 12,
    color: '#d1d5db',
    fontWeight: '500',
  },
  preciosInfo: {
    marginTop: 12,
    backgroundColor: '#334155',
    borderRadius: 12,
    padding: 12,
  },
  precioRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  precioLabel: {
    fontSize: 12,
    color: '#cbd5e1',
    fontWeight: '500',
  },
  precioValor: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  precioValorDestacado: {
    fontSize: 13,
    color: '#3b82f6',
    fontWeight: 'bold',
  },
  statusIndicators: {
    flex: 1,
    alignItems: 'flex-end',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusBar: {
    width: 28,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  statusLabel: {
    fontSize: 11,
    color: '#cbd5e1',
    fontWeight: '500',
  },
  botonesCard: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-start',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  loadingText: {
    color: '#ffffff',
    marginTop: 12,
    fontSize: 16,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyText: {
    color: '#cbd5e1',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 16,
  },
  detallesContainer: {
    flex: 1,
  },
  formulario: {
    flex: 1,
  },
  section: {
    marginBottom: 24,
  },
  subTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#334155',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    gap: 16,
  },
  infoItem: {
    flex: 1,
    minWidth: '45%',
  },
  infoLabel: {
    color: '#cbd5e1',
    fontSize: 12,
    marginBottom: 4,
    fontWeight: '500',
  },
  infoValue: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  productosSection: {
    marginBottom: 20,
  },
  productosHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  btnAnadirProducto: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#6b7280',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnAnadirTexto: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  formularioProducto: {
    backgroundColor: '#4b5563',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  botonesFormularioProducto: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-end',
    marginTop: 16,
  },
  btnGuardarProducto: {
    backgroundColor: '#3b82f6',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  btnCancelarProducto: {
    backgroundColor: '#6b7280',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  tablaProductos: {
    backgroundColor: '#334155',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
  },
  tablaHeader: {
    flexDirection: 'row',
    backgroundColor: '#4b5563',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  tablaHeaderText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  tablaFila: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#4b5563',
    paddingVertical: 12,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  tablaCelda: {
    justifyContent: 'center',
  },
  tablaCeldaTexto: {
    color: '#cbd5e1',
    fontSize: 12,
    textAlign: 'center',
  },
  materialSubtext: {
    fontSize: 10,
    color: '#94a3b8',
    fontStyle: 'italic',
  },
  unidadSubtext: {
    fontSize: 10,
    color: '#94a3b8',
    textAlign: 'center',
  },
  estatusPill: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
    minWidth: 60,
    alignItems: 'center',
  },
  estatusTexto: {
    fontSize: 10,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  estatusEntregado: {
    backgroundColor: '#22c55e',
  },
  estatusPendiente: {
    backgroundColor: '#eab308',
  },
  accionBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: '#374151',
  },
  accionBtnEliminar: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: '#ef4444',
  },
  emptyProductos: {
    backgroundColor: '#374151',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyProductosText: {
    color: '#9ca3af',
    fontSize: 14,
    fontStyle: 'italic',
  },
  resumenContainer: {
    backgroundColor: '#334155',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    flexDirection: 'row',
    gap: 16,
  },
  resumenIzquierda: {
    flex: 2,
  },
  resumenDerecha: {
    flex: 1,
    alignItems: 'flex-end',
  },
  resumenFila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  resumenLabel: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '500',
  },
  resumenValor: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  ivaLabel: {
    color: '#3b82f6',
    fontSize: 14,
    fontWeight: 'bold',
  },
  ivaValor: {
    color: '#3b82f6',
    fontSize: 14,
    fontWeight: 'bold',
  },
  totalLabel: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  totalValor: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  estadoIndicadores: {
    marginBottom: 16,
  },
  estadoFila: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  estadoBarra: {
    width: 24,
    height: 6,
    borderRadius: 3,
  },
  estadoTexto: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '500',
  },
  botonesEstado: {
    gap: 8,
  },
  btnEstado: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minWidth: 80,
    justifyContent: 'center',
  },
  btnPagado: {
    backgroundColor: '#22c55e',
  },
  btnSinPagar: {
    backgroundColor: '#ef4444',
  },
  btnEntregado: {
    backgroundColor: '#3b82f6',
  },
  btnPendienteEntrega: {
    backgroundColor: '#eab308',
  },
  btnEstadoTexto: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  botonesAcciones: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 12,
    marginTop: 16,
  },
  btnImprimir: {
    backgroundColor: '#6366f1',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
    justifyContent: 'center',
  },
  btnImprimirTexto: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  btnEditarPedido: {
    backgroundColor: '#eab308',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
    justifyContent: 'center',
  },
  btnEliminarPedido: {
    backgroundColor: '#ef4444',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
    justifyContent: 'center',
  },
  row2: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  col2: {
    flex: 1,
    minWidth: 150,
  },
  input: {
    backgroundColor: '#1e293b',
    marginBottom: 12,
  },
  pickerContainer: {
    backgroundColor: '#1e293b',
    borderWidth: 1,
    borderColor: '#3b82f6',
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 12,
  },
  picker: {
    color: '#ffffff',
    height: 50,
    backgroundColor: '#1e293b',
  },
  facturaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: '#3b82f6',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewCalculos: {
    backgroundColor: '#4b5563',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
  },
  calculosGrid: {
    gap: 10,
  },
  calculoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  calculoLabel: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '500',
  },
  calculoValor: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  botonesForm: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginTop: 24,
    marginBottom: 16,
  },
  btnGuardar: {
    backgroundColor: '#22c55e',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
    justifyContent: 'center',
    maxWidth: 150,
  },
  // Estilos de paginación
  paginationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: '#334155',
    marginTop: 8,
  },
  paginationButton: {
    backgroundColor: '#1e293b',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#334155',
  },
  paginationButtonDisabled: {
    backgroundColor: '#0f172a',
    borderColor: '#1e293b',
  },
  paginationInfo: {
    alignItems: 'center',
  },
  paginationText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  paginationSubtext: {
    color: '#94a3b8',
    fontSize: 12,
    marginTop: 2,
  },
  // Estilos para la información del producto
  productoInfoContainer: {
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  productoInfoTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  productoInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  productoInfoItem: {
    flex: 1,
    minWidth: '45%',
  },
  productoInfoLabel: {
    color: '#94a3b8',
    fontSize: 11,
    marginBottom: 2,
  },
  productoInfoValue: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  productoInfoTotal: {
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: '#4b5563',
    paddingTop: 8,
    marginTop: 8,
  },
  productoInfoTotalValue: {
    color: '#3b82f6',
    fontSize: 16,
  },

  botonesProductosHeader: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  btnGuardar: {
    backgroundColor: '#22c55e',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  cambiosPendientesAlert: {
    backgroundColor: '#fef3c7',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
  },
  cambiosPendientesText: {
    color: '#92400e',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
  },


});

export default styles;